### PR TITLE
feature: remove agent logic from external-health-monitor

### LINKED ISSUE #57: Remove agent from external-health-monitor now that it is in Kubelet
With this PR https://github.com/kubernetes/kubernetes/pull/99284/, the health monitoring logic is moved from the external agent to Kubelet.  We should remove the agent in 1.21.

### PR DESCRIPTION
**Pull request by fengzixu**
**What type of PR is this?**

/kind feature
**What this PR does / why we need it**:

1. remove agent logic of external-health-monitor-agent

**Which issue(s) this PR fixes**:

Fixes #57

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
- remove the logic of external-health-monitor-agent due to they are moved to kubelet
```

### CODE REVIEW

**Comment by xing-yang** [comment]
> Should we wait some time and do this when the agent logic in kubelet goes to beta ?

Probably makes sense.  In that case, we should disable the agent logic and not to release a new image for it.

**Comment by xing-yang** [comment]
Let's put this PR on-hold until CSIVolumeHealth feature in Kubelet moves to Beta.

@fengzixu, can you submit another PR to disable the building of the agent image?  I think just removing it from the Makefile will do.  Thanks.
https://github.com/kubernetes-csi/external-health-monitor/blob/master/Makefile

**Comment by fengzixu** [comment]
> Let's put this PR on-hold until CSIVolumeHealth feature in Kubelet moves to Beta.
> 
> @fengzixu, can you submit another PR to disable the building of the agent image? I think just removing it from the Makefile will do. Thanks.
> https://github.com/kubernetes-csi/external-health-monitor/blob/master/Makefile

Done: https://github.com/kubernetes-csi/external-health-monitor/pull/64

**Comment by xing-yang** [comment]
We moved agent logic to Kubelet in 1.21. In 1.24, we also added volume health as metrics in Kubelet and made a second Alpha. I think the agent logic should be removed from this repo so we don't have to maintain code in two places.

@NickrenREN What do you think?

**Comment by NickrenREN** [comment]
@xing-yang sorry for the late reply. Sound good to me

**Comment by xing-yang** [comment]
@fengzixu Can you update this PR?

**Comment by fengzixu** [comment]
Will fix the issue in test soon

**Pull request merged**
