### PR TITLE
Add github template, git ignore and release scripts for this repo

### PR DESCRIPTION
**Pull request by NickrenREN**
Add github template, git ignore and release scripts for this repo

```release-note
NONE
```

### CODE REVIEW

**Comment by NickrenREN** [comment]
/assign @xing-yang 

Add some common files and scripts that repositories under kubernetes-csi org all have. 
PTAL
Thanks.

**Comment by msau42** [comment]
release-tools needs to be updated according to the instructions under release-tools/README.

We have some verify- scripts that check for modifications made to files under release-tools, and they will fail if the commit history is not the same.

**Comment by xing-yang** [comment]
I think you need to pull the original commits from https://github.com/kubernetes-csi/csi-release-tools.  See this PR for example: https://github.com/kubernetes-csi/external-snapshotter/pull/86

CC @pohly

**Comment by NickrenREN** [comment]
ran `git subtree add --prefix=release-tools https://github.com/kubernetes-csi/csi-release-tools.git master`

@msau42 @pohly could you help take a look ?  
Thanks

**Pull request merged**
